# Variables

@baseurl = http://localhost:3333

# Health check
# @name healthCheck
GET {{baseurl}}/health

### 

# Get rooms
# @name getRooms
GET {{baseurl}}/rooms

###

# Create rooms
# @name createRoom
POST {{baseurl}}/rooms
Content-Type: application/json

{
    "name": "Sala de teste",
    "description": "O amor venceu, faz o L"
}

###

@roomId = {{createRoom.response.body.$.roomId}}

###

# Get room questions
# @name getRoomQuestions
GET {{baseurl}}/rooms/{{roomId}}/questions

###

# Create question
# @name createQuestion
POST {{baseurl}}/rooms/{{roomId}}/questions
Content-Type: application/json

{
    "question": "Qual o conceito de x dentro de y?"
}